# -*- coding: utf-8 -*-
"""analyze_feature_combinations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1THxMrHEgjXzlvm4u5VM1LO6lgc25O9kT
"""

import os
import pandas as pd
from itertools import combinations

# Path to the CSV file and output folder
input_file_path = 'output1/results.csv'
output_folder = 'output2'
output_file_path = os.path.join(output_folder, 'analysis.csv')

# Create the directory if it does not exist
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

# Read CSV data into a DataFrame
df = pd.read_csv(input_file_path)

# List of features that occurred 5 or more times
features_with_5_or_more = [
    "Market Force Indicator", "Volume_Float_Ratio", "Volume Per Minute",
    "Relative Volume", "Short Ratio", "Volume Per Minute Institutional Transactions"
]

# Extract top features and their importances from the DataFrame
feature_importances = {}
for index, row in df.iterrows():
    for i in range(1, 26):  # Top 25 Features
        feature_name = row.get(f"Top {i} Feature", None)
        feature_importance = row.get(f"Top {i} Importance", None)
        if feature_name in features_with_5_or_more:
            if feature_name not in feature_importances:
                feature_importances[feature_name] = []
            feature_importances[feature_name].append(float(feature_importance))

# Calculate average importance for each feature
average_importances = {feature: sum(importances)/len(importances)
                       for feature, importances in feature_importances.items()}

# Generate all possible combinations of 3 features
feature_combinations = list(combinations(features_with_5_or_more, 3))

# Evaluate combinations
results = []
for combo in feature_combinations:
    feature1, feature2, feature3 = combo
    avg_importance1 = average_importances.get(feature1, 0)
    avg_importance2 = average_importances.get(feature2, 0)
    avg_importance3 = average_importances.get(feature3, 0)
    combined_importance = avg_importance1 + avg_importance2 + avg_importance3  # Sum of importances
    results.append({
        "Feature 1": feature1,
        "Feature 2": feature2,
        "Feature 3": feature3,
        "Combined Importance": combined_importance
    })

# Create a DataFrame for the results
results_df = pd.DataFrame(results)

# Sort results by combined importance in descending order
results_df = results_df.sort_values(by="Combined Importance", ascending=False)

# Save the results to a CSV file
results_df.to_csv(output_file_path, index=False)

print(f"Results have been saved to {output_file_path}")